DROP TABLE IF EXISTS game;

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  game_id TEXT NOT NULL,
  guess TEXT NOT NULL,
  life INTEGER NOT NULL,
  player TEXT,
  pokemon_id TEXT NOT NULL,
  score INTEGER NOT NULL,
  streak INTEGER NOT NULL
);